config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/users", to: "users#create"

  get "/mypage", to: "users#show"

  root 'timer#index'


end

app/models/alarm_setting.rb
class AlarmSetting < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/timer_setting.rb
class TimerSetting < ApplicationRecord
  belongs_to :user, optional: true

  validates :study_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :short_break_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :long_break_time, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :set_count_before_long_break, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/models/work_record.rb
class WorkRecord < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: "ログインしました"
    else
      flash.now[:alert] = "ログインできませんでした。<br>入力した内容に誤りがあります。"
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: "ログアウトしました"
  end
end

app/controllers/timer_controller.rb
class TimerController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_name: params[:user_name], email: params[:email], password: params[:password])
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "サインアップしました"
    else
      flash.now[:alert] = "サインアップできませんでした"
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/timer_helper.rb
module TimerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PomodoroTimer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="header">
      <%= link_to root_path, class: "logo" do %>
        One's PomoTimer
      <%end%>
      <div class="nav">
        <% if session[:user_id] %>
          <%= link_to "マイページ", mypage_path, class: "nav-link" %>
        <% else %>
          <%= link_to "ログイン", login_path, class: "nav-link" %>
          <%= link_to "サインアップ", signup_path, class: "nav-link" %>
        <% end %>
      </div>
    </div>

    <%= yield %>
  </body>
</html>

app/views/timer/index.html.erb
<h1>One's PomoTimer</h1>

<div data-controller="timer">
  <div data-timer-target="display" class="timer-display">25:00</div>

  <button data-action="click->timer#start" data-timer-target="startButton" class="start-button">START</button>

  <div class="button-group">
    <button data-action="click->timer#stop" data-timer-target="stopButton" disabled>STOP</button>
    <button data-action="click->timer#reset" data-timer-target="resetButton">RESET</button>
  </div>

  <div class="input-group">
    <label><span>作業時間 </span><input type="number" data-action="change->timer#updateStudyTime" value="25"></label>
    <label><span>小休憩 </span><input type="number" data-action="change->timer#updateShortBreakTime" value="5"></label>
    <label><span>大休憩 </span><input type="number" data-action="change->timer#updateLongBreakTime" value="15"></label>
    <label><span>ポモドーロセット数 </span><input type="number" data-action="change->timer#updateSetCountBeforeLongBreak" value="4"></label>
  </div>
</div>

app/views/users/new.html.erb
<h1>サインアップ</h1>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

<%= form_with url: users_path, method: :post do |f| %>
  <div class="form-group">
    <%= f.label :user_name, "ユーザー名" %>
    <%= f.text_field :user_name %>
  </div>
  <div class="form-group">
    <%= f.label :email, "メールアドレス" %>
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.label :password, "パスワード" %>
    <%= f.password_field :password %>
  </div>
  <div class="form-group">
    <%= f.submit "サインアップ" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>

<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<div class="user-info">
  <div class="user-name"><%= @user.user_name %></div>
  <div class="user-email"><%= @user.email %></div>
</div>

<%= form_with url: logout_path, method: :delete, class: "logout-form" do |f| %>
  <%= f.submit "ログアウト", class: "logout-button" %>
<% end %>